blank_issues_enabled: false
contact_links:
  - name: ğŸ“ æ–‡æ¡£æ”¹è¿›
    url: https://github.com/netsora/SoraBot-website/issues/new?assignees=&labels=documentation&projects=&template=document.yml&title=Docs%3A+
    about: æ–‡æ¡£é”™è¯¯åŠæ”¹è¿›æ„è§åé¦ˆ
  - name: SoraBot è®ºå›
    url: https://github.com/orgs/netsora/discussions
    about: å‰å¾€ SoraBot è®ºå›æé—®
